# Generated by Django 3.2.4 on 2021-09-05 09:34

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django_countries.fields
import phonenumber_field.modelfields
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('publish', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True, verbose_name='creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='modification date and time')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(default='', editable=False, max_length=255, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('image', stdimage.models.StdImageField(help_text='upload post cover Image', upload_to='tongoza/posts/images/products')),
                ('caption', models.TextField(help_text='Inspire your audience with the moment captured in this image')),
                ('public', models.BooleanField(default=True, help_text='Everyone can see this post.')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True, verbose_name='creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='modification date and time')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(default='', editable=False, max_length=255, unique=True)),
                ('aboutMe', models.CharField(max_length=400)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('education_institution', models.CharField(blank=True, max_length=200, null=True)),
                ('course', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=60, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=150, null=True)),
                ('facebook', models.CharField(blank=True, max_length=150, null=True)),
                ('twitter', models.CharField(blank=True, max_length=150, null=True)),
                ('telegram_username', models.CharField(blank=True, max_length=60, null=True)),
                ('snapchat_username', models.CharField(blank=True, max_length=60, null=True)),
                ('messenger', models.CharField(blank=True, max_length=60, null=True)),
                ('whatsapp_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('city', models.CharField(blank=True, max_length=60, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('government_issued_id', stdimage.models.StdImageField(blank=True, help_text='Required only if you wish to have a dual profile for both Tongoza light mode and Tongoza darke mode', null=True, upload_to='tongoza/images/national_identificantions/')),
            ],
            options={
                'db_table': 'Light Mode Profile',
                'abstract': False,
            },
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True, verbose_name='creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='modification date and time')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', stdimage.models.StdImageField(upload_to='tongoza/images/profile_images')),
                ('caption', models.TextField(blank=True, help_text='Write something about the moment captured in this image', null=True)),
                ('public', models.BooleanField(default=True)),
                ('in_display', models.BooleanField(default=True)),
                ('profile_pic', models.BooleanField(default=False)),
                ('dark_mode_pic', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tongozahome.profile')),
            ],
            options={
                'ordering': ('-in_display',),
            },
            managers=[
                ('displayed', django.db.models.manager.Manager()),
            ],
        ),
    ]
