# Generated by Django 3.2.4 on 2021-09-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tongozahome', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='profile_pic',
            field=models.BooleanField(default=True),
        ),
    ]
